version: '3'

services:

  nginx:
    container_name: nginx
    networks:
      - inception-network
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env 
    volumes:
      - /home/bgrulois/data/wordpress 
    restart: unless-stopped
  
  mariadb:
    container_name: mariadb
    networks:
      - inception-network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    depends_on: 
      - nginx
    volumes:
      - /home/bgrulois/data/mariadb
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception-network
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/home/bgrulois/data/wordpress
    restart: on-failure

volumes: 
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bgrulois/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bgrulois/data/mariadb'

networks:
  inception-network:
    driver: bridge
